language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t austenvalentine/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true austenvalentine/docker-react npm run test -- --coverage
